# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer', '0003_auto_20180930_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
